name: benchmark-test

on:
  workflow_dispatch:
    inputs:
      repository:
        type: string
        description: repo name
      url:
        type: string
        description: pr url
      pr_id:
        type: string
        description: pr id

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      -
        name: ${{ github.event.inputs.url }}
        uses: actions/checkout@v3
      -
        name: Setup julia
        uses: julia-actions/setup-julia@v1
      -
        name: Build pkg
        uses: julia-actions/julia-buildpkg@v1
      -
        id: benchmark
        name: Run benchmark
        run: |
          flux=true julia --project=. benchmark/benchmarks.jl
      -
        name: Comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.inputs.pr_id }}
          repository: ${{ github.event.inputs.repository }}
          body: |
            Hi! This is a comment by GitHub Actions!
